### ISSUE TITLE
Failure on fetching definitions in Windows 8.1 Anki 2.0.32

### ISSUE THREAD

**Issue by lsmgeb89** [z1lc/AutoDefine#1]
Here is the log.
![image 1](https://cloud.githubusercontent.com/assets/1487128/8078558/17761f4e-0f91-11e5-8154-4e526f3ddfac.png)

**Comment by z1lc** [comment]
Could you post what text you were using in the first field of the note? That way I can reproduce the error.

**Comment by lsmgeb89** [comment]
I cannot remember the exact word I used for testing.
I just type a common word to test like "apple", "home", etc.

**Comment by z1lc** [comment]
I haven't been able to reproduce this in the latest release.
Please re-open this issue if you still see this happening and we can try to investigate further.
