### ISSUE TITLE
Parse error for word 'test'

### ISSUE THREAD

**Issue by M-Razavi** [z1lc/AutoDefine#12]
Anki Version: 2.1.5
Platform: Windows 10
URL: http://www.dictionaryapi.com/api/v1/references/collegiate/xml/test?key=77c9e2ea-c1b6-482b-af44-696203812386
Stack Trace: Traceback (most recent call last):  File C:\Users\int\AppData\Roaming\Anki2\addons21\2136497008\autodefine.py, line 103, in _get_definition    etree = ET.fromstring(urllib.request.urlopen(url).read())  File xml\etree\ElementTree.py, line 1314, in XML  File <string>, line Nonexml.etree.ElementTree.ParseError: syntax error: line 1, column 0

**Comment by z1lc** [comment]
Thanks for reporting, looks like this is due to your key being invalid (the URL returns "Invalid API key or reference name provided."). Using my own key I get the correct response for the word 'test'.

I'll add some error handling to the code to detect this and alert the user.

**Comment by M-Razavi** [comment]
I registered for another key and problem solved. tnx

**Comment by z1lc** [comment]
Fixed in deb1b214a690bf42143a4f6f52ce5045d856b277
