### ISSUE TITLE
Medical Dictionary not fetching definitions

### ISSUE THREAD

**Issue by PMcManus09** [z1lc/AutoDefine#15]
This is the error that I get: 

Caught exception:
  File "aqt/progress.py", line 67, in handler
  File "/Users/***/Library/Application Support/Anki2/addons21/2136497008/autodefine.py", line 90, in <lambda>
    editor.saveNow(lambda: _get_definition(editor, force_pronounce, force_definition))
  File "/Users/***/Library/Application Support/Anki2/addons21/2136497008/autodefine.py", line 192, in _get_definition
    word = clean_html(editor.note.fields[0]).strip()
<class 'AttributeError'>: 'NoneType' object has no attribute 'fields'

Also, I get this some times as well: 

Didn't find definition for word 'hematuria'
Using URL 'https://www.dictionaryapi.com/api/references/medical/v2/xml/hematuria?key=***'

***: Used to redact personal info. 

P.s: Thanks for addressing this suggested update so quickly. 

EDIT: Now working perfectly. Thanks!

**Comment by PMcManus09** [comment]
Actually, it is working for me now. It will pop up as an error listed as the second example above but will generate the audio and definition.

**Comment by z1lc** [comment]
Fixed display of tool tips in c51d80d69e461770a5936736e0cf82ab7fc13817
