### ISSUE TITLE
Phonetic Pronunciation Symbols

### ISSUE THREAD

**Issue by ShahrokhBahtooei** [z1lc/AutoDefine#21]
Hi kindly guys,
I appreciate your efforts in simplifying English learning :) I wanted to include written phonetic pronunciation of the word in my flashcards. You know, it seems more precise to me. Can I do that with this add-on?
Cheers

**Comment by z1lc** [comment]
Currently, the add-on doesn't support phonetic pronunciations. However, if you'd like to have a go at implementing it yourself, the api documentation is available [here](https://www.dictionaryapi.com/).
