### ISSUE TITLE
[question] Is there a way to use AutoDefine to pronounce certain terms in pre-made decks on demand?

### ISSUE THREAD

**Issue by bradydjohnson** [z1lc/AutoDefine#38]
Hi there,

To start, thanks for creating & sharing this add-on. The installation instructions & vid is very clear. I'm wondering if I could use this add-on to help me learn how to pronounce certain terms in pre-made Anki decks. 

I'm envisioning being able to highlight a word while reviewing, right-clicking or invoking a keyboard shortcut, then the pronunciation being announced. Is there any way AutoDefine can do this?

**Comment by z1lc** [comment]
There's no functionality right now that does this in review, though selecting a word and then using a keyboard shortcut will insert the pronunciation into the defined field in the editing/add cards view. If you'd like to extend AutoDefine to do what you're describing, I'm happy to review PRs!

**Comment by bradydjohnson** [comment]
I figured out a way to do what I want with AwesomeTTS. Thanks for your quick reply. If I were a programmer, I would def try to work on my own pull request!
