### ISSUE TITLE
Support for learner dictionary API 

### ISSUE THREAD

**Issue by AbdelrahmanHamdy1996** [z1lc/AutoDefine#40]

**Comment by AbdelrahmanHamdy1996** [comment]
https://learnersdictionary.com/
Mariam webster learner dictionary is better for non-native speaker, more clear example and so on, so it is great to make this addon support the learner dictionary API

**Comment by z1lc** [comment]
Looks like this is available via https://www.dictionaryapi.com/products/api-learners-dictionary -- could be integrated the [same way we've integrated the Medical dictionary API](https://github.com/z1lc/AutoDefine/commit/cf31ffa3d5a5067e8b74652e5f99f3129c99b5ea).
