### ISSUE TITLE
Can any support be added from wording.info for picture dictionary.

### ISSUE THREAD

**Issue by arshapplied** [z1lc/AutoDefine#41]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Debug info:**
 - Anki Version [e.g. 2.1.5]
 - OS: [Linux, Mac, Windows]

**Additional context (e.g., exception)**

**Comment by z1lc** [comment]
Looks like this isn't a bug -- please update the description accordingly. Feel free to create a new issue when you do.
