### ISSUE TITLE
'No entry found'

### ISSUE THREAD

**Issue by RlearnerR** [z1lc/AutoDefine#42]
When using the AutoDefine add-on, Anki states '**No entry found in Merriam-Webster dictionary for word 'x'.** It does this for all words, for example 'test' (x = given word). Screenshot attached below. 

I have added my API key, and have tried uninstalling and re-installing the add-on. My anki version is:
Version 2.1.14 (7b93e985)
Qt 5.12.1 PyQt 5.11.3

Very grateful for any guidance - this looks like a fantastic add-on! 

Thanks,
Max

<img width="771" alt="Screenshot 2020-07-22 at 09 48 52" src="https://user-images.githubusercontent.com/48523777/88151082-84e7b500-cc02-11ea-83a2-debb90d62a62.png">

**Comment by z1lc** [comment]
Huh, that's interesting -- normally we'd see an error somewhere earlier. Only thing that's jumping out is that you're on a fairly old version of Anki -- if you're not relying on older add-ons working with that version, I would say try to update to 2.1.28 (current) and see if the issue persists.

**Comment by RlearnerR** [comment]
Aha yep updating has fixed it, I should've tried that first! Thank you for your help!
