### ISSUE TITLE
Cannot fetch some words, such as "vice"

### ISSUE THREAD

**Issue by nhap96** [z1lc/AutoDefine#5]
![image](https://cloud.githubusercontent.com/assets/14961828/10267122/0e608900-6ab1-11e5-876f-1ad1ea939cfc.png)

I think putting "if entry.find("fl") == None: continue" at line 90 in core.py should work.

**Comment by z1lc** [comment]
Thank you for the reproducible example.
This has now been fixed in 35c40087a7eeec521bb4e3d43d2bf24f3e3bf14d.
