### ISSUE TITLE
Word is in field number 2

### ISSUE THREAD

**Issue by AAbdelsameia** [z1lc/AutoDefine#52]
Do I have to have the word I want to define in field 0? I currently have the words I want to define in field 2 of all my cards; would it be possible that I use field 2 as the source?

**Comment by z1lc** [comment]
You can either select the word manually and use the extension, or you can change the code here to make it come from an arbitrary field:
https://github.com/z1lc/AutoDefine/blob/master/AutoDefineAddon/autodefine.py#L241
